"""empty message

Revision ID: 44e9522aa307
Revises: caa388717934
Create Date: 2023-12-11 17:19:19.868042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44e9522aa307'
down_revision: Union[str, None] = 'caa388717934'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('space_shop',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(), nullable=True),
    sa.Column('product_price', sa.BigInteger(), nullable=True),
    sa.Column('product_photo', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('chat_id', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('space_shop')
    # ### end Alembic commands ###
