"""empty message

Revision ID: 7e88b7739093
Revises: 6e21c152f5ad
Create Date: 2023-12-13 16:48:01.242345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e88b7739093'
down_revision: Union[str, None] = '6e21c152f5ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('space_shop', sa.Column('contact', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('space_shop', 'contact')
    # ### end Alembic commands ###
